openapi: 3.0.3
info:
  title: ABN Lookup
  description: ABN lookup demo
  termsOfService: http://swagger.io/terms/
  contact:
    email: mohit.f.aggarwal@accenture.com
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://t7snohiumi.execute-api.ap-southeast-2.amazonaws.com/develop
tags:
  - name: lookup
    description: ABN lookup
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /lookup:
    get:
      tags:
        - lookup
      summary: ABN Lookup
      description: Multiple status values can be provided with comma separated strings
      operationId: abnLookup
      parameters:
        - name: abn
          in: query
          description: abn value to be queried
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/AbnLookUpResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorised
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Not Allowed
        '408':
          description: Request Timeout
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
        '501':
          description: Method Not Implemented


components:
  schemas:

    AbnLookUpResponse:
      type: object
      properties:
        EntityName:
          type: string
        ABNStatus:
          type: string
        EntityType:
          type: string
        GST:
          type: string
        MainBusinessLocation:
          type: string

    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
